# Trading Strategy Configuration

# Data Settings
data:
  default_provider: "yahoo"
  cache_enabled: true
  cache_directory: "./cache"
  default_frequency: "1d"
  lookback_days: 252
  
# Risk Management
risk:
  initial_capital: 100000
  max_position_size: 0.1
  max_portfolio_risk: 0.02
  max_drawdown: 0.2
  max_leverage: 1.0
  max_concentration: 0.3
  var_limit: 0.05
  stop_loss: 0.02
  take_profit: 0.05

# Backtesting
backtesting:
  commission: 0.001
  slippage: 0.0005
  min_commission: 1.0
  execution_model: "close"
  use_adjusted_close: true
  benchmark: "SPY"
  risk_free_rate: 0.02

# Strategy Parameters
strategies:
  momentum:
    lookback_period: 20
    holding_period: 5
    num_stocks: 10
    position_sizing: "equal_weight"
    rebalance_frequency: "daily"
  
  mean_reversion:
    lookback_period: 20
    entry_threshold: 2.0
    exit_threshold: 0.5
    use_bollinger_bands: true
    position_sizing: "risk_based"
  
  pairs_trading:
    lookback_period: 60
    entry_threshold: 2.0
    exit_threshold: 0.5
    correlation_threshold: 0.7

# Portfolio Optimization
portfolio:
  risk_free_rate: 0.02
  regularization_factor: 0.001
  use_robust_covariance: true
  rebalance_frequency: "monthly"
  min_weight: 0.0
  max_weight: 0.3
  max_turnover: 1.0

# Logging
logging:
  level: "INFO"
  file: "logs/trading_strategy.log"
  max_file_size: "10MB"
  backup_count: 5

# Database (if needed)
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  name: "trading_data"
  user: "trader"
  # password should be set via environment variable

# API Keys (set via environment variables)
api_keys:
  alpha_vantage: "${ALPHA_VANTAGE_API_KEY}"
  polygon: "${POLYGON_API_KEY}"
  iex: "${IEX_API_KEY}"

# Universe definitions
universes:
  sp500:
    - "AAPL"
    - "MSFT" 
    - "GOOGL"
    - "AMZN"
    - "TSLA"
    - "META"
    - "NVDA"
    - "JPM"
    - "JNJ"
    - "V"
  
  crypto:
    - "BTC-USD"
    - "ETH-USD"
    - "ADA-USD"
    - "DOT-USD"
    - "LINK-USD"
  
  etfs:
    - "SPY"
    - "QQQ"
    - "IWM"
    - "EFA"
    - "EEM"
    - "VNQ"
    - "GLD"
    - "TLT"